name: ShellCheck CI
on: [push]

jobs:
  check-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Run ShellCheck for all shell scripts
        uses: ludeeus/action-shellcheck@master
